export default constants={
  SAVE_USER_INFO_FROM_FACEBOOK:'SAVE_USER_INFO_FROM_FACEBOOK',
  SAVE_TODO:"SAVE_TODO",
  SAVE_USER_INFO_FROM_GOOGLE:"SAVE_USER_INFO_FROM_GOOGLE",
  DELETE_TODO:"DELETE_TODO",
  EDIT_TODO:"EDIT_TODO",
  SAVE_NAME_EMAIL:"SAVE_NAME_EMAIL",
  REPLACE_TODO:"REPLACE_TODO",
  CLEAR_DATA:"CLEAR_DATA",
}
